<?php

namespace AppBundle\Repository;

/**
 * EnfermedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfermedadRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Retorna las enfermedades del sistema ordenados ASC por nombre
     */
    public function findAllOrderedByNombre() {
        return $this->createQueryBuilder('enfermedad')
                        ->orderBy("enfermedad.nombre", "ASC")
                        ->getQuery()->getResult();
    }

}
