<?php

namespace AppBundle\Repository;

/**
 * FactorRiesgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactorRiesgoRepository extends \Doctrine\ORM\EntityRepository
{
}
