<?php

namespace AppBundle\Repository;

/**
 * FactorRiesgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactorRiesgoRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Retorna los factores de riesgo del sistema ordenados ASC por username
     */
    public function findAllOrderedByNombre() {
        return $this->createQueryBuilder('factorriesgo')
                        ->orderBy("factorriesgo.nombre", "ASC")
                        ->getQuery()->getResult();
    }

}
