<?php

namespace AppBundle\Repository;

/**
 * InscriptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptoRepository extends \Doctrine\ORM\EntityRepository
{
}
