<?php

namespace AppBundle\Repository;

/**
 * InscriptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptoRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Retorna los Inscriptos del sistema ordenados ASC por apellido
     */
    public function findAllOrderedByApellidoOld() {
        return $this->createQueryBuilder('inscripto')
                        ->orderBy("inscripto.apellido", "ASC")
                        ->getQuery()->getResult();
    }

     /**
     * Retorna los Inscriptos del sistema ordenados ASC por apellido
     */
    public function findAllOrderedByApellido($desdeFecha, $hastaFecha) {
        return $this->createQueryBuilder('inscripto')
    				->andWhere('inscripto.fechaInscripcion > :desde')
                    ->andWhere('inscripto.fechaInscripcion < :hasta')
        			->setParameter('desde', $desdeFecha)
                    ->setParameter('hasta', $hastaFecha)
                    ->orderBy("inscripto.apellido", "ASC")
                    ->getQuery()->getResult();
    }

}
