<?php

namespace AppBundle\Repository;

/**
 * NoCargadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoCargadoRepository extends \Doctrine\ORM\EntityRepository
{
}
