<?php

namespace AppBundle\Repository;

/**
 * NoDocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoDocenteRepository extends \Doctrine\ORM\EntityRepository
{
}
