<?php

namespace AppBundle\Repository;

/**
 * NoDocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoDocenteRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Retorna los no-docentes del sistema ordenados ASC por apellido
     */
    public function findAllOrderedByApellido() {
        return $this->createQueryBuilder('nodocente')
                        ->orderBy("nodocente.apellido", "ASC")
                        ->getQuery()->getResult();
    }

}
