<?php

namespace AppBundle\Repository;

/**
 * RegistroEnfermedadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroEnfermedadesRepository extends \Doctrine\ORM\EntityRepository
{
}
