<?php

namespace AppBundle\Repository;

/**
 * RegistroFactorRiesgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroVacunacionRepository extends \Doctrine\ORM\EntityRepository
{
}
