<?php

namespace AppBundle\Repository;

/**
 * VacunaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacunaRepository extends \Doctrine\ORM\EntityRepository
{
}
