<?php

namespace AppBundle\Repository;

/**
 * VacunaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacunaRepository extends \Doctrine\ORM\EntityRepository {

    public function getVacunasCalendario() {
        return $this->createQueryBuilder('vacuna')
                        ->where('vacuna.esObligatoria = true')->getQuery()->getResult();
    }
    
    public function getVacunasOptativas() {
        return $this->createQueryBuilder('vacuna')
                        ->where('vacuna.esObligatoria = false')->getQuery()->getResult();
    }

}
