<?php

namespace AppBundle\Repository;

/**
 * VisitanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitanteRepository extends \Doctrine\ORM\EntityRepository
{
}
